export const SET_APP_READY = 'SET_APP_READY';

export const GET_COUPONS_FROM_BASE = 'GET_COUPONS_FROM_BASE';
export const SET_ACTIVE_COUPON = 'SET_ACTIVE_COUPON';

export const OPEN_COPY_MODAL = 'OPEN_COPY_MODAL';
export const CLOSE_COPY_MODAL = 'CLOSE_COPY_MODAL';
